name: Build and Deploy on GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - "animations/**"
      - "css/**"
      - "scripts/**"
      - "index_template.html"
      - ".github/workflows/**"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  SITE_DIR: _site

jobs:
  check-titles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6.1
        with:
          python-version: '3.13'

      - name: Run name test script
        run: python3 ./scripts/check_titles.py

  build:
    runs-on: ubuntu-latest
    needs: check-titles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6.1
        with:
          python-version: '3.13'

      - name: Create index
        run: python3 ./scripts/create_index.py
      - name: Prepare files for deployment
        run: |
          mkdir -p ${{ env.SITE_DIR }}
          cp index.html ${{ env.SITE_DIR }}/
          cp -r css ${{ env.SITE_DIR }}/
          cp -r animations ${{ env.SITE_DIR }}/
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SITE_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
