name: Check Animations

on:
  push:
    paths:
      - "animations/**"
      - "scripts/**"
      - ".github/workflows/check-animations.yml"
  workflow_call:

jobs:
  check-animations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r ./scripts/requirements.txt

      - name: Run folder check
        run: python3 ./scripts/check_animations.py

